### ISSUE TITLE
Error: Invalid value for '-A' / '--app': 

### ISSUE THREAD

**Issue by ndz2011** [aixplain/tts-qa-public#4]
/usr/bin/celery:22: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point

Could not download 'pyannote/segmentation' model.
It might be because the model is private or gated so make
sure to authenticate. Visit https://hf.co/settings/tokens to
create your access token and retry with:

   >>> Model.from_pretrained('pyannote/segmentation',
   ...                       use_auth_token=YOUR_AUTH_TOKEN)

If this still does not work, it might be because the model is gated:
visit https://hf.co/pyannote/segmentation to accept the user conditions.
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app':

**Comment by ahmetgunduz** [comment]
have you set  env variables here: https://github.com/aixplain/tts-qa/blob/main/secrets.env.example

You need to convert this file and rename it as `secrets.env` and put the necessary api tokens. For pyannote huggingface'token is needed

**Comment by ndz2011** [comment]
Hi, thanks for your reply. I added huggingface token and now get an new error. My celery version is 5.3.6:

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module src.service.tasks the following error occurred:
Traceback (most recent call last):
  File "/home/ndz2011/anaconda3/envs/aixplain/lib/python3.10/site-packages/celery/app/utils.py", line 383, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/home/ndz2011/anaconda3/envs/aixplain/lib/python3.10/site-packages/kombu/utils/imports.py", line 64, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'src.service' has no attribute 'tasks'
